groups:
- name: bbl-latest
  jobs:
  - unit-tests
  - deploy-app

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: bbl-latest-app
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
    paths:
    - apps/bbl-latest
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{pws_username}}
    password: {{pws_password}}
    organization: {{pws_organization}}
    space: {{pws_space}}

jobs:
- name: unit-tests
  public: true
  plan:
  - aggregate:
    - get: bbl-latest-app
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/misc/bbl-latest/unit-tests/task.yml
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
- name: deploy-app
  public: true
  plan:
  - get: bbl-latest-app
    passed: [unit-tests]
    trigger: true
  - put: pws
    params:
      manifest: bbl-latest-app/apps/bbl-latest/manifest.yml
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
