groups:
- name: bosh-test
  jobs:
  - test-bosh-test

resources:
- name: bosh-test
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/bosh-test.git
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

jobs:
- name: test-bosh-test
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-test
      trigger: true
  - task: test
    file: ci/scripts/bosh-test/task.yml
