groups:
- name: bosh-bootloader
  jobs:
  - test-bosh-bootloader
  - aws-integration-tests
  - gcp-integration-tests
  - concourse-integration-tests
- name: final-release
  jobs:
  - major
  - minor
  - patch
  - github-release
- name: cf-deployment
  jobs:
  - downstream-infrastructure-docker-image
  - setup-infrastructure
  - destroy-infrastructure

resources:
- name: bosh-bootloader-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/bosh-bootloader.git
- name: bosh-bootloader-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-bootloader.git
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: infrastructure-ci-env
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/infrastructure-ci-env.git
    private_key: {{infrastructure_ci_env_private_key}}
- name: bbl-integration-s3
  type: s3
  source:
    bucket: bbl-integration-tests
    regexp: (.*).tgz
    access_key_id: {{bbl_integration_tests_s3_access_key_id}}
    secret_access_key: {{bbl_integration_tests_s3_secret_access_key}}
- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: s3
    bucket: bbl-version
    key: bbl-version
    access_key_id: {{bbl_version_s3_access_key_id}}
    secret_access_key: {{bbl_version_s3_secret_access_key}}
- name: bbl-release
  type: github-release
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_github_access_token}}

# CF Deployment Concourse Tasks Resource
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v1.*

- name: cf-deployment-concourse-tasks-docker-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

- name: cf-deployment-concourse-tasks-bbl-dev-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/cf-deployment-concourse-tasks-bbl-dev
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: cf-deployment-concourse-tasks-bbl-dev-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/cf-deployment-concourse-tasks-bbl-dev

jobs:

# Main Pipeline
- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      trigger: true
  - task: test
    file: ci/scripts/bosh-bootloader/test-bosh-bootloader/task.yml

- name: aws-integration-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/bosh-bootloader/aws-integration/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_REGION: {{aws_region}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: gcp-integration-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/bosh-bootloader/gcp-integration/task.yml
    params:
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE: {{gcp_zone}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: concourse-integration-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [aws-integration-tests, gcp-integration-tests]
      trigger: true
  - task: test
    file: ci/scripts/bosh-bootloader/concourse-integration/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_REGION: {{aws_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE: {{gcp_zone}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

# Final Release Pipeline
- name: major
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: major}

- name: minor
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: minor}

- name: patch
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: patch}

- name: github-release
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-version
      trigger: true
      resource: version
    - get: bosh-bootloader
      resource: bosh-bootloader-master
  - task: build-binaries
    file: ci/scripts/bosh-bootloader/build-final-release/task.yml
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/bbl-*

# CF Deployment Pipeline
- name: downstream-infrastructure-docker-image
  public: true
  plan:
  - do:
    - aggregate:
      - get: cf-deployment-concourse-tasks-docker-image
        trigger: true
      - get: infrastructure-ci
        resource: cf-deployment-concourse-tasks-bbl-dev-dockerfile
        trigger: true
    - put: cf-deployment-concourse-tasks-bbl-dev-docker-image
      params:
        build: infrastructure-ci/dockerfiles/cf-deployment-concourse-tasks-bbl-dev
        cache: false

- name: setup-infrastructure
  serial_groups: [downstream]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: infrastructure-ci-env
    - get: cf-deployment-concourse-tasks-bbl-dev-docker-image
      passed: [downstream-infrastructure-docker-image]
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    image: cf-deployment-concourse-tasks-bbl-dev-docker-image
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: us-east1
      BBL_GCP_ZONE: us-east1-b
      BBL_LB_CERT: {{bbl_downstream_cf_ssl_cert}}
      BBL_LB_KEY: {{bbl_downstream_cf_ssl_cert_private_key}}
      LB_DOMAIN: bbl-downstream.bbl-test.ci.cf-app.com
      BBL_ENV_NAME: bbl-downstream
      BBL_STATE_DIR: bbl-downstream-env
    input_mapping:
      bbl-state: infrastructure-ci-env
    ensure:
      put: infrastructure-ci-env
      params:
        repository: updated-bbl-state
        rebase: true

- name: destroy-infrastructure
  serial_groups: [downstream]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: infrastructure-ci-env
    - get: cf-deployment-concourse-tasks-bbl-dev-docker-image
      passed: [setup-infrastructure]
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    image: cf-deployment-concourse-tasks-bbl-dev-docker-image
    input_mapping:
      bbl-state: infrastructure-ci-env
    ensure:
      put: infrastructure-ci-env
      params:
        repository: updated-bbl-state
        rebase: true
