groups:
- name: bosh-bootloader
  jobs:
  - test-bosh-bootloader
  - aws-integration-tests
  - gcp-integration-tests
  - concourse-integration-tests
- name: final-release
  jobs:
  - major
  - minor
  - patch
  - github-release

resources:
- name: bosh-bootloader-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/bosh-bootloader.git
- name: bosh-bootloader-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-bootloader.git
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: bbl-integration-s3
  type: s3
  source:
    bucket: bbl-integration-tests
    regexp: (.*).tgz
    access_key_id: {{bbl_integration_tests_s3_access_key_id}}
    secret_access_key: {{bbl_integration_tests_s3_secret_access_key}}
- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: s3
    bucket: bbl-version
    key: bbl-version
    access_key_id: {{bbl_version_s3_access_key_id}}
    secret_access_key: {{bbl_version_s3_secret_access_key}}
- name: bbl-release
  type: github-release
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_github_access_token}}

jobs:
- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      trigger: true
  - task: test
    file: ci/scripts/bosh-bootloader/test-bosh-bootloader/task.yml

- name: aws-integration-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/bosh-bootloader/aws-integration/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_REGION: {{aws_region}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: gcp-integration-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/bosh-bootloader/gcp-integration/task.yml
    params:
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE: {{gcp_zone}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: concourse-integration-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-develop
      passed: [aws-integration-tests, gcp-integration-tests]
      trigger: true
  - task: test
    file: ci/scripts/bosh-bootloader/concourse-integration/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_REGION: {{aws_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE: {{gcp_zone}}
    on_failure:
      put: bbl-integration-s3
      params:
        file: bbl-integration-s3/*.tgz

- name: major
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: major}

- name: minor
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: minor}

- name: patch
  public: true
  plan:
  - get: version
  - put: version
    params: {bump: patch}

- name: github-release
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-version
      trigger: true
      resource: version
    - get: bosh-bootloader
      resource: bosh-bootloader-master
  - task: build-binaries
    file: ci/scripts/bosh-bootloader/build-final-release/task.yml
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/bbl-*
