groups:
- name: bosh-deployment
  jobs:
  - bump-deployments
  - test-bosh-bootloader
  - aws-acceptance-tests
  - gcp-acceptance-tests
  - commit-bump-deployments-change
  - github-release

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: jumpbox-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cppforlife/jumpbox-deployment.git

- name: bosh-bootloader
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/bosh-bootloader.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: bosh-bootloader-bump-deployments-ci
  type: git
  source:
    branch: bump-deployments-ci
    uri: git@github.com:cloudfoundry/bosh-bootloader.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: s3
    bucket: bbl-version
    key: bbl-version
    access_key_id: {{bbl_version_s3_access_key_id}}
    secret_access_key: {{bbl_version_s3_secret_access_key}}

- name: bbl-release
  type: github-release
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_github_access_token}}

jobs:
- name: bump-deployments
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
    - get: bosh-deployment
      trigger: true
    - get: jumpbox-deployment
      trigger: true
  - task: bump-deployments
    file: ci/scripts/bosh-deployment/bump-deployments/task.yml
  - put: bump-deployments-ci
    resource: bosh-bootloader-bump-deployments-ci
    params:
      repository: bump-deployments-ci
      force: true

- name: test-bosh-bootloader
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [bump-deployments]
      trigger: true
  - task: test
    file: ci/scripts/bosh-bootloader/test-bosh-bootloader/task.yml

- name: aws-acceptance-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/bosh-bootloader/aws-acceptance/task.yml
    params:
      BBL_IAAS: aws
      BBL_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      BBL_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      BBL_AWS_REGION: {{aws_region}}
      BBL_TEST_ENV_ID_PREFIX: bump-deployments

- name: gcp-acceptance-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/bosh-bootloader/gcp-acceptance/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_TEST_ENV_ID_PREFIX: bump-deployments

- name: commit-bump-deployments-change
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader-bumped
      resource: bosh-bootloader-bump-deployments-ci
      passed: [aws-acceptance-tests, gcp-acceptance-tests]
      trigger: true
  - task: commit-bosh-deployment-change
    file: ci/scripts/bosh-deployment/commit-bosh-deployment-change/task.yml
    on_failure:
      put: slack-alert
      params:
        text: |
          [$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME] failed:

          https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - put: bosh-bootloader
    params:
      repository: bosh-bootloader

- name: github-release
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-version
      resource: version
      params: {bump: patch}
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      trigger: true
      passed: [commit-bump-deployments-change]
  - task: build-binaries
    file: ci/scripts/bosh-bootloader/build-final-release/task.yml
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      body: builds/body
      globs:
      - builds/bin/bbl-*
  - put: version
    params: {file: bbl-version/version}
