groups:
- name: bosh-test
  jobs:
  - test-bosh-test

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: bosh-test
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/bosh-test.git
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:
- name: test-bosh-test
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-test
      trigger: true
  - task: test
    file: ci/scripts/misc/bosh-test/task.yml
    on_failure:
      put: slack-alert
      params:
        text: |
          [$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME] failed:

          https://p-concourse.wings.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
