groups:
- name: check-a-record
  jobs:
  - test-check-a-record

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: check-a-record
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/check-a-record.git
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:
- name: test-check-a-record
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: check-a-record
      trigger: true
  - task: test
    file: ci/scripts/misc/check-a-record/task.yml
    on_failure:
      put: slack-alert
      params:
        text: |
          [$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME] failed:

          https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
