---
groups:
- name: consul
  jobs:
  - check-git-submodules
  - test-confab
  - consats-linux
  - consats-linux-turbulence
  - consats-windows
  - consats-windows-turbulence
  - deploy-with-cf
  - deploy-with-diego
  - run-cats
  - delete-cf-deployments
  - create-final-release
  - merge-master-into-develop
  - deploy-bosh-lite-manifests
  - deploy-aws-manifests
- name: cleanup
  jobs:
  - delete-consats-linux-deployments
  - delete-consats-windows-deployments
- name: infrastructure
  jobs:
  - setup-consats-linux-infrastructure
  - teardown-consats-linux-infrastructure
  - setup-consats-windows-infrastructure
  - teardown-consats-windows-infrastructure

resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git

- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: consul-cf-env
  type: git
  source:
    branch: master
    private_key: {{consul-cf-env-private-key}}
    uri: git@github.com:cloudfoundry/consul-cf-env.git

- name: infrastructure-ci-bbl-states
  type: git
  source:
    branch: master
    private_key: {{cf_infra_bot_user_github_private_key}}
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz

- name: cf-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-release.git

- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry/diego-release.git

- name: latest-consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release

- name: turbulence-release
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: repo
      resource: consul-release-develop
      trigger: true
  - task: check-git-submodules
    file: ci/scripts/check-git-submodules/task.yml

- name: test-confab
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [check-git-submodules]
      trigger: true
  - task: test-confab
    file: ci/scripts/test-confab/task.yml

- name: consats-linux
  public: true
  serial: true
  serial_groups: [consats]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-confab]
      trigger: true
    - get: stemcell
      resource: gcp-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: latest-consul-release
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: consats-linux
    file: ci/scripts/run-consats/task.yml
    params:
      BBL_STATE_DIR: consats-linux
      PARALLEL_NODES: 7
      ENABLE_TURBULENCE_TESTS: false

- name: consats-linux-turbulence
  public: true
  serial: true
  serial_groups: [consats]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [consats-linux]
      trigger: true
    - get: stemcell
      resource: gcp-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: latest-consul-release
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: consats-linux
    file: ci/scripts/run-consats/task.yml
    params:
      BBL_STATE_DIR: consats-linux
      PARALLEL_NODES: 1
      ENABLE_TURBULENCE_TESTS: true

- name: consats-windows
  public: true
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-confab]
      trigger: true
    - get: stemcell
      resource: gcp-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: latest-consul-release
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: consats-windows
    file: ci/scripts/run-consats/task.yml
    params:
      BBL_STATE_DIR: consats-windows
      PARALLEL_NODES: 5
      ENABLE_TURBULENCE_TESTS: false
      WINDOWS_CLIENTS: true

- name: consats-windows-turbulence
  public: true
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [consats-windows]
      trigger: true
    - get: stemcell
      resource: gcp-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: latest-consul-release
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: consats-windows
    file: ci/scripts/run-consats/task.yml
    params:
      BBL_STATE_DIR: consats-windows
      PARALLEL_NODES: 1
      ENABLE_TURBULENCE_TESTS: true
      WINDOWS_CLIENTS: true

- name: deploy-with-cf
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: consul-cf-env
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [consats-linux-turbulence, consats-windows-turbulence]
      trigger: true
    - get: cf-release
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-consul-cf
    file: ci/scripts/deploy-consul-cf/task.yml
    params:
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}

- name: deploy-with-diego
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: consul-cf-env
    - get: ci
      resource: infrastructure-ci
    - get: diego-release
      resource: diego-release-master
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-cf]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-consul-diego
    file: ci/scripts/deploy-consul-diego/task.yml
    params:
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}

- name: run-cats
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: run-cats
    file: ci/scripts/run-cats/task.yml
    params:
      CF_DOMAIN: {{consul_cf_domain}}
      CF_USER: {{consul_cf_user}}
      CF_PASSWORD: {{consul_cf_password}}
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}
      DEPLOYMENT_NAME: consul-cf-deployment

- name: delete-cf-deployments
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [run-cats]
      trigger: true
  - task: delete-deployments
    file: ci/scripts/delete-deployments/task.yml
    params:
      BOSH_ENVIRONMENT: {{consul_cf_bosh_director}}
      BOSH_CLIENT: {{consul_cf_bosh_user}}
      BOSH_CLIENT_SECRET: {{consul_cf_bosh_password}}
      BOSH_CA_CERT: {{consul_cf_bosh_ca_cert}}
      DEPLOYMENTS_WITH_WORD: consul-cf-deployment

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: consul-release-develop
      passed: [delete-cf-deployments]
      trigger: true
    - get: release-repo-master
      resource: consul-release-master
  - task: create-final-release
    file: ci/scripts/create-final-release/task.yml
    params:
      RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: ci/scripts/merge-master-into-develop/task.yml
  - put: consul-release-merge-target
    params:
      repository: final-release-repo

- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: release
      resource: consul-release-develop
      passed: [consats-linux-turbulence]
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: ci/scripts/deploy-bosh-lite-manifests/task.yml
    params:
      BOSH_AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      BOSH_AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
      BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
      BOSH_LITE_NAME: bosh-lite-consul
      BOSH_LITE_KEYPAIR: bosh-lite
      BOSH_LITE_PRIVATE_KEY_CONTENTS: {{bosh-lite-private-key}}
      MANIFESTS: "manifests/bosh-lite/3-node-with-ssl.yml"

- name: deploy-aws-manifests
  public: true
  plan:
  - aggregate:
    - get: infrastructure-ci
    - get: release
      resource: consul-release-develop
      passed: [consats-linux-turbulence]
      trigger: true
  - task: deploy-aws-manifests
    file: ci/scripts/deploy-aws-manifests/deploy-consul-aws-manifests.yml
    params:
      BOSH_DIRECTOR: {{consats_linux_bosh_director}}
      BOSH_USER: {{consats_linux_bosh_username}}
      BOSH_PASSWORD: {{consats_linux_bosh_password}}
      AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{infrastructure_account_aws_default_region}}
      MANIFEST_PATH: manifests/aws/multi-az-ssl.yml

- name: delete-consats-linux-deployments
  public: false
  serial: true
  serial_groups: [consats-linux]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: delete-deployments
    file: ci/scripts/delete-deployments/task.yml
    params:
      BBL_STATE_DIR: consats-linux
      DEPLOYMENTS_WITH_WORD: consul

- name: delete-consats-windows-deployments
  public: false
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: delete-deployments
    file: ci/scripts/delete-deployments/task.yml
    params:
      BBL_STATE_DIR: consats-windows
      DEPLOYMENTS_WITH_WORD: consul

# Infrastructure

- name: setup-consats-linux-infrastructure
  public: true
  serial: true
  serial_groups: [consats-linux]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-up
    file: ci/scripts/infrastructure/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: consats-linux
      BBL_NAME: consats-linux
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true

- name: teardown-consats-linux-infrastructure
  public: true
  serial: true
  serial_groups: [consats-linux]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-destroy
    file: ci/scripts/infrastructure/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: consats-linux
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true

- name: setup-consats-windows-infrastructure
  public: true
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-up
    file: ci/scripts/infrastructure/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: consats-windows
      BBL_NAME: consats-windows
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true

- name: teardown-consats-windows-infrastructure
  public: true
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-destroy
    file: ci/scripts/infrastructure/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: consats-windows
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true
