---
groups:
- name: consul
  jobs:
  - check-git-submodules
  - test-confab
  - consats-linux
  - consats-linux-turbulence
  - consats-windows
  - consats-windows-turbulence
  - deploy-with-cf
  - deploy-with-diego
  - run-cats
  - delete-cf-deployments
  - create-final-release
  - merge-master-into-develop
  - deploy-bosh-lite-manifests

resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git

- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: consul-cf-env
  type: git
  source:
    branch: master
    private_key: {{consul-cf-env-private-key}}
    uri: git@github.com:cloudfoundry/consul-cf-env.git

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz

- name: cf-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-release.git

- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry/diego-release.git

- name: bosh-aws-cpi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bosh-aws-cpi-release

- name: latest-consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release

- name: turbulence-release
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: repo
      resource: consul-release-develop
      trigger: true
  - task: check-git-submodules
    file: ci/scripts/check-git-submodules/task.yml

- name: test-confab
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [check-git-submodules]
      trigger: true
  - task: test-confab
    file: ci/scripts/test-confab/task.yml

- name: consats-linux
  public: true
  serial: true
  serial_groups: [consats]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-confab]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: bosh-aws-cpi-release
    - get: latest-consul-release
  - task: consats-linux
    file: ci/scripts/run-consats/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      AWS_REGION: {{infrastructure_account_aws_default_region}}
      AWS_SECURITY_GROUP_NAME: {{infrastructure_account_aws_security_group_name}}
      AWS_SUBNETS: {{infrastructure_account_aws_subnets}}
      AWS_CLOUD_CONFIG_SUBNETS: {{infrastructure_account_aws_cloud_config_subnets}}
      AWS_DEFAULT_KEY_NAME: {{infrastructure_account_aws_default_key_name}}
      BOSH_DIRECTOR: {{bosh_director}}
      BOSH_USER: {{bosh_username}}
      BOSH_PASSWORD: {{bosh_password}}
      BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_STATIC_IP: {{bosh_errand_cloud_config_network_static_ip}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_AZ: {{bosh_errand_cloud_config_network_az}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_NAME: {{bosh_errand_cloud_config_network_name}}
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_PERSISTENT_DISK_TYPE: 1GB
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_VM_TYPE: m3.medium
      REGISTRY_USERNAME: {{registry_username}}
      REGISTRY_PASSWORD: {{registry_password}}
      REGISTRY_HOST: 10.0.0.6
      PARALLEL_NODES: 7
      ENABLE_TURBULENCE_TESTS: false

- name: consats-linux-turbulence
  public: true
  serial: true
  serial_groups: [consats]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [consats-linux]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: bosh-aws-cpi-release
    - get: latest-consul-release
  - task: consats-linux-turbulence
    file: ci/scripts/run-consats/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      AWS_REGION: {{infrastructure_account_aws_default_region}}
      AWS_SECURITY_GROUP_NAME: {{infrastructure_account_aws_security_group_name}}
      AWS_SUBNETS: {{infrastructure_account_aws_subnets}}
      AWS_CLOUD_CONFIG_SUBNETS: {{infrastructure_account_aws_cloud_config_subnets}}
      AWS_DEFAULT_KEY_NAME: {{infrastructure_account_aws_default_key_name}}
      BOSH_DIRECTOR: {{bosh_director}}
      BOSH_USER: {{bosh_username}}
      BOSH_PASSWORD: {{bosh_password}}
      BOSH_DIRECTOR_CA_CERT: {{bosh_director_ca_cert}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_STATIC_IP: {{bosh_errand_cloud_config_network_static_ip}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_AZ: {{bosh_errand_cloud_config_network_az}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_NAME: {{bosh_errand_cloud_config_network_name}}
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_PERSISTENT_DISK_TYPE: 1GB
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_VM_TYPE: m3.medium
      REGISTRY_USERNAME: {{registry_username}}
      REGISTRY_PASSWORD: {{registry_password}}
      REGISTRY_HOST: 10.0.0.6
      PARALLEL_NODES: 1
      ENABLE_TURBULENCE_TESTS: true

- name: consats-windows
  public: true
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [test-confab]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: bosh-aws-cpi-release
    - get: latest-consul-release
  - task: consats-windows
    file: ci/scripts/run-consats/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      AWS_REGION: {{windows_aws_default_region}}
      AWS_SECURITY_GROUP_NAME: {{windows_aws_security_group_name}}
      AWS_SUBNETS: {{windows_aws_subnets}}
      AWS_CLOUD_CONFIG_SUBNETS: {{windows_aws_cloud_config_subnets}}
      AWS_DEFAULT_KEY_NAME: {{windows_aws_default_key_name}}
      BOSH_DIRECTOR: {{windows_bosh_director}}
      BOSH_USER: {{windows_bosh_username}}
      BOSH_PASSWORD: {{windows_bosh_password}}
      BOSH_DIRECTOR_CA_CERT: {{windows_bosh_director_ca_cert}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_STATIC_IP: {{windows_bosh_errand_cloud_config_network_static_ip}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_AZ: {{windows_bosh_errand_cloud_config_network_az}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_NAME: {{windows_bosh_errand_cloud_config_network_name}}
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_PERSISTENT_DISK_TYPE: 1GB
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_VM_TYPE: m3.medium
      REGISTRY_USERNAME: {{windows_registry_username}}
      REGISTRY_PASSWORD: {{windows_registry_password}}
      REGISTRY_HOST: 10.0.0.6
      PARALLEL_NODES: 5
      ENABLE_TURBULENCE_TESTS: false
      WINDOWS_CLIENTS: true

- name: consats-windows-turbulence
  public: true
  serial: true
  serial_groups: [consats-windows]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [consats-windows]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
    - get: windows-stemcell
    - get: turbulence-release
    - get: bosh-aws-cpi-release
    - get: latest-consul-release
  - task: consats-windows-turbulence
    file: ci/scripts/run-consats/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      AWS_REGION: {{windows_aws_default_region}}
      AWS_SECURITY_GROUP_NAME: {{windows_aws_security_group_name}}
      AWS_SUBNETS: {{windows_aws_subnets}}
      AWS_CLOUD_CONFIG_SUBNETS: {{windows_aws_cloud_config_subnets}}
      AWS_DEFAULT_KEY_NAME: {{windows_aws_default_key_name}}
      BOSH_DIRECTOR: {{windows_bosh_director}}
      BOSH_USER: {{windows_bosh_username}}
      BOSH_PASSWORD: {{windows_bosh_password}}
      BOSH_DIRECTOR_CA_CERT: {{windows_bosh_director_ca_cert}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_STATIC_IP: {{windows_bosh_errand_cloud_config_network_static_ip}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_AZ: {{windows_bosh_errand_cloud_config_network_az}}
      BOSH_ERRAND_CLOUD_CONFIG_NETWORK_NAME: {{windows_bosh_errand_cloud_config_network_name}}
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_PERSISTENT_DISK_TYPE: 1GB
      BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_VM_TYPE: m3.medium
      REGISTRY_USERNAME: {{windows_registry_username}}
      REGISTRY_PASSWORD: {{windows_registry_password}}
      REGISTRY_HOST: 10.0.0.6
      PARALLEL_NODES: 1
      ENABLE_TURBULENCE_TESTS: true
      WINDOWS_CLIENTS: true

- name: deploy-with-cf
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: consul-cf-env
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [consats-linux-turbulence]
      trigger: true
    - get: cf-release
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-consul-cf
    file: ci/scripts/deploy-consul-cf/task.yml
    params:
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}

- name: deploy-with-diego
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: consul-cf-env
    - get: ci
      resource: infrastructure-ci
    - get: diego-release
      resource: diego-release-master
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-cf]
      trigger: true
    - get: stemcell
      resource: aws-stemcell
  - task: deploy-consul-diego
    file: ci/scripts/deploy-consul-diego/task.yml
    params:
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}

- name: run-cats
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: run-cats
    file: ci/scripts/run-cats/task.yml
    params:
      CF_DOMAIN: {{consul_cf_domain}}
      CF_USER: {{consul_cf_user}}
      CF_PASSWORD: {{consul_cf_password}}
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}
      DEPLOYMENT_NAME: consul-cf-deployment

- name: delete-cf-deployments
  public: true
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: consul-release
      resource: consul-release-develop
      passed: [run-cats]
      trigger: true
  - task: delete-deployments
    file: ci/scripts/delete-deployments/task.yml
    params:
      BOSH_DIRECTOR: {{consul_cf_bosh_director}}
      BOSH_USER: {{consul_cf_bosh_user}}
      BOSH_PASSWORD: {{consul_cf_bosh_password}}
      DEPLOYMENTS_WITH_WORD: consul-cf-deployment

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: consul-release-develop
      passed: [delete-cf-deployments]
      trigger: true
    - get: release-repo-master
      resource: consul-release-master
  - task: create-final-release
    file: ci/scripts/create-final-release/task.yml
    params:
      RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: ci/scripts/merge-master-into-develop/task.yml
  - put: consul-release-merge-target
    params:
      repository: final-release-repo

- name: deploy-bosh-lite-manifests
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: release
      resource: consul-release-develop
      passed: [consats-linux-turbulence]
      trigger: true
  - task: deploy-bosh-lite-manifests
    file: ci/scripts/deploy-bosh-lite-manifests/task.yml
    params:
      BOSH_AWS_ACCESS_KEY_ID: {{infrastructure_account_aws_access_key_id}}
      BOSH_AWS_SECRET_ACCESS_KEY: {{infrastructure_account_aws_secret_access_key}}
      BOSH_LITE_SECURITY_GROUP: {{bosh_lite_security_group}}
      BOSH_LITE_SUBNET_ID: {{bosh_lite_subnet_id}}
      BOSH_LITE_NAME: bosh-lite-consul
      BOSH_LITE_KEYPAIR: bosh-lite
      BOSH_LITE_PRIVATE_KEY_CONTENTS: {{bosh-lite-private-key}}
      MANIFESTS: "manifests/bosh-lite/3-node-with-ssl.yml"
