groups:
- name: etcd
  jobs:
  - check-git-submodules
  - test-etcd-proxy
  - test-etcd-metrics-server
  - eats
  - eats-turbulence
  - deploy-sample-manifests
  - deploy-cf-cats
  - run-cats
  - delete-cf-cats
  - deploy-cf-tls-upgrade
  - run-cf-tls-upgrade
  - delete-cf-tls-upgrade
  - create-final-release
  - merge-master-into-develop
- name: cleanup
  jobs:
  - delete-eats-deployments
- name: infrastructure
  jobs:
  - setup-eats-infrastructure
  - teardown-eats-infrastructure
  - setup-cf-cats-infrastructure
  - teardown-cf-cats-infrastructure
  - setup-cf-tls-upgrade-infrastructure
  - teardown-cf-tls-upgrade-infrastructure

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: etcd-release-develop
  type: git
  source:
    branch: develop
    ignore_paths:
    - .final_builds
    - releases
    uri: https://github.com/cloudfoundry-incubator/etcd-release.git

- name: etcd-release-master
  type: git
  source:
    branch: master
    private_key: {{etcd_release_private_key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git

- name: etcd-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{etcd_release_private_key}}
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git

- name: cf-deployment
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: infrastructure-ci-bbl-states
  type: git
  source:
    branch: master
    private_key: {{cf_infra_bot_user_github_private_key}}
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: turbulence-release
  type: github-release
  source:
    repository: turbulence-release
    user: christianang

- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release

- name: latest-etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release

- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

- name: empty-ops-files
  type: time
  source: {interval: 5m}

- name: cats-concourse-task
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cats-concourse-task.git

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: repo
      trigger: true
      resource: etcd-release-develop
  - task: check-git-submodules
    file: ci/scripts/common/check-git-submodules/task.yml
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: test-etcd-proxy
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: etcd-release
      passed:
      - check-git-submodules
      trigger: true
      resource: etcd-release-develop
  - task: test-etcd-proxy
    file: ci/scripts/etcd/test-etcd-proxy/task.yml
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: test-etcd-metrics-server
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: etcd-release
      passed:
      - check-git-submodules
      trigger: true
      resource: etcd-release-develop
  - task: test-etcd-metrics-server
    file: ci/scripts/etcd/test-etcd-metrics-server/task.yml
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: eats
  public: true
  serial: true
  serial_groups:
  - eats
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: etcd-release
      passed:
      - test-etcd-proxy
      - test-etcd-metrics-server
      trigger: true
      resource: etcd-release-develop
    - get: stemcell
      resource: gcp-stemcell
    - get: turbulence-release
    - get: consul-release
    - get: latest-etcd-release
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: run-eats
    file: ci/scripts/etcd/run-eats/task.yml
    params:
      BBL_STATE_DIR: eats
      ENABLE_TURBULENCE_TESTS: false
      PARALLEL_NODES: 7
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: eats-turbulence
  public: true
  serial: true
  serial_groups:
  - eats
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: etcd-release
      passed:
      - eats
      trigger: true
      resource: etcd-release-develop
    - get: stemcell
      passed:
      - eats
      resource: gcp-stemcell
    - get: turbulence-release
    - get: consul-release
    - get: latest-etcd-release
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: run-eats
    file: ci/scripts/etcd/run-eats/task.yml
    params:
      BBL_STATE_DIR: eats
      ENABLE_TURBULENCE_TESTS: true
      PARALLEL_NODES: 3
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: deploy-sample-manifests
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-deployment
    - get: bosh-lite-stemcell
    - get: release
      resource: etcd-release-develop
      passed: [eats-turbulence]
      trigger: true
  - task: deploy-sample-manifests
    file: ci/scripts/common/deploy-sample-manifests/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      CLOUD_CONFIG: manifests/cloud-config.yml
      MANIFESTS: manifests/3-node-with-ssl.yml manifests/3-node-no-ssl.yml manifests/3-node-with-proxy.yml
      DEPENDENCIES: cloudfoundry-incubator/consul-release
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: deploy-cf-cats
  public: true
  serial_groups: [cf-cats]
  plan:
  - aggregate:
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: ops-files
      resource: empty-ops-files
    - get: release
      resource: etcd-release-develop
      passed: [eats-turbulence]
      trigger: true
    - get: vars-store
      resource: infrastructure-ci-bbl-states
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-cats
  - task: deploy
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-cats
      SYSTEM_DOMAIN: etcd-cf-cats.infrastructure.cf-app.com
      VARS_STORE_FILE: etcd-cf-cats/deployment-vars.yml
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: updated-vars-store
        rebase: true
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: run-cats
  public: true
  serial_groups: [cf-cats]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: integration-configs
      resource: infrastructure-ci
    - get: vars-store
      resource: infrastructure-ci-bbl-states
    - get: cats-concourse-task
    - get: cf-acceptance-tests
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
      passed: [deploy-cf-cats]
      trigger: true
    - get: release
      resource: etcd-release-develop
      passed: [deploy-cf-cats]
  - task: update-integration-config
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    params:
      CATS_INTEGRATION_CONFIG_FILE: artifacts/cats_config.json
      VARS_STORE_FILE: etcd-cf-cats/deployment-vars.yml
      SYSTEM_DOMAIN: etcd-cf-cats.infrastructure.cf-app.com
  - task: run-cats
    file: cats-concourse-task/task.yml
    input_mapping: {integration-config: updated-integration-configs }
    params:
      CONFIG_FILE_PATH: artifacts/cats_config.json
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
  - put: slack-alert
    params:
      icon_emoji: ":white_check_mark:"
      text: |
        [$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME] passed!

- name: delete-cf-cats
  public: true
  serial_groups: [cf-cats]
  plan:
  - aggregate:
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
      passed: [run-cats]
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: release
      resource: etcd-release-develop
      passed: [run-cats]
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-cats
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: deploy-cf-tls-upgrade
  public: true
  serial_groups: [cf-tls-upgrade]
  plan:
  - aggregate:
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: infrastructure-ci
    - get: ops-files
      resource: empty-ops-files
    - get: release
      resource: etcd-release-develop
      passed: [eats-turbulence]
      trigger: true
    - get: vars-store
      resource: infrastructure-ci-bbl-states
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
  - task: deploy
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      OPS_FILES: infrastructure-ci/scripts/etcd/opsfiles/non-tls-cf-deployment.yml
      SYSTEM_DOMAIN: etcd-cf-tls-upgrade.infrastructure.cf-app.com
      VARS_STORE_FILE: etcd-cf-tls-upgrade/deployment-vars.yml
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: updated-vars-store
        rebase: true
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: run-cf-tls-upgrade
  serial_groups: [cf-tls-upgrade]
  plan:
  - aggregate:
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
      passed: [deploy-cf-tls-upgrade]
      trigger: true
    - get: infrastructure-ci
    - get: etcd-release
      trigger: true
      resource: etcd-release-develop
      passed: [eats-turbulence]
  - task: run-cf-tls-upgrade
    file: infrastructure-ci/scripts/etcd/test-cf-tls-upgrade/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      CF_DOMAIN: {{etcd_cf_domain}}
      CF_PASSWORD: {{etcd_cf_password}}
      CF_USER: {{etcd_cf_user}}
      DEPLOYMENT_NAME: etcd-cf-tls-upgrade
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: delete-cf-tls-upgrade
  public: true
  serial_groups: [cf-tls-upgrade]
  plan:
  - aggregate:
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
      passed: [run-cf-tls-upgrade]
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: release
      resource: etcd-release-develop
      passed: [run-cf-tls-upgrade]
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: oss-s3-buckets-stack
    - get: release-repo
      resource: etcd-release-develop
      passed: [delete-cf-cats, delete-cf-tls-upgrade]
      trigger: true
    - get: release-repo-master
      resource: etcd-release-master
  - task: create-final-release
    file: ci/scripts/common/create-final-release/task.yml
    params:
      RELEASE_NAME: etcd
  - put: etcd-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo-master
      trigger: true
      resource: etcd-release-master
    - get: release-repo
      resource: etcd-release-merge-target
  - task: merge-master-into-develop
    file: ci/scripts/common/merge-master-into-develop/task.yml
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
  - put: etcd-release-merge-target
    params:
      repository: final-release-repo
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: delete-eats-deployments
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: delete-deployments
    file: ci/scripts/common/delete-deployments/task.yml
    params:
      BBL_STATE_DIR: eats
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: setup-eats-infrastructure
  public: true
  serial: true
  serial_groups:
  - eats
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-up
    file: ci/scripts/common/bbl-up/task.yml
    params:
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_NAME: eats
      BBL_STATE_DIR: eats
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        rebase: true
        repository: bbl-states-repo-out

- name: teardown-eats-infrastructure
  public: true
  serial: true
  serial_groups:
  - eats
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      passed:
      - setup-eats-infrastructure
      resource: infrastructure-ci-bbl-states
  - task: bbl-destroy
    file: ci/scripts/common/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: eats
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        rebase: true
        repository: bbl-states-repo-out

- name: setup-cf-cats-infrastructure
  public: true
  serial: true
  serial_groups: [cf-cats]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-up
    file: ci/scripts/common/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: etcd-cf-cats
      BBL_NAME: etcd-cf-cats
      BBL_LB_DOMAIN: etcd-cf-cats.infrastructure.cf-app.com
      BBL_LB_CERT: {{etcd_cf_deployment_lb_cert}}
      BBL_LB_KEY: {{etcd_cf_deployment_lb_key}}
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: teardown-cf-cats-infrastructure
  public: true
  serial: true
  serial_groups: [cf-cats]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
      passed: [setup-cf-cats-infrastructure]
  - task: bbl-destroy
    file: ci/scripts/common/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-cats
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: setup-cf-tls-upgrade-infrastructure
  public: true
  serial: true
  serial_groups: [cf-tls-upgrade]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-up
    file: ci/scripts/common/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      BBL_NAME: etcd-cf-tls-upgrade
      BBL_LB_DOMAIN: etcd-cf-tls-upgrade.infrastructure.cf-app.com
      BBL_LB_CERT: {{etcd_cf_deployment_lb_cert}}
      BBL_LB_KEY: {{etcd_cf_deployment_lb_key}}
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}

- name: teardown-cf-tls-upgrade-infrastructure
  public: true
  serial: true
  serial_groups: [cf-tls-upgrade]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
      passed: [setup-cf-tls-upgrade-infrastructure]
  - task: bbl-destroy
    file: ci/scripts/common/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true
    on_failure:
      put: slack-alert
      params:
        text: {{slack_failure_text}}
