groups:
- name: etcd
  jobs:
  - check-git-submodules
  - test-etcd-proxy
  - test-etcd-consistency-checker
  - test-etcdfab
  - test-etcd-metrics-server
  - eats
  - deploy-sample-manifests
  - cats
  - cf-tls-upgrade
  - create-final-release
  - merge-master-into-develop

resources:
- name: infrastructure-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
    branch: master

- name: etcd-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/etcd-release.git
    branch: develop
    ignore_paths:
    - .final_builds
    - releases

- name: etcd-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
    branch: master
    private_key: {{etcd_release_private_key}}

- name: etcd-release-merge-target
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/etcd-release.git
    branch: develop
    private_key: {{etcd_release_private_key}}

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: develop

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: infrastructure-ci-bbl-states
  type: git
  source:
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git
    branch: master
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: turbulence-release
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release

- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release

- name: latest-etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
    branch: master

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: oss-s3-buckets-stack
  type: git
  source:
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}

- name: cats-concourse-task
  type: git
  source:
    uri: https://github.com/cloudfoundry/cats-concourse-task.git
    branch: master

- name: cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
    branch: master

jobs:
- name: check-git-submodules
  public: true
  serial: true
  plan:
  - aggregate:
    - get: repo
      resource: etcd-release-develop
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: check-git-submodules
    file: ci/scripts/common/check-git-submodules/task.yml

- name: test-etcd-proxy
  public: true
  plan:
  - aggregate:
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - check-git-submodules
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test-etcd-proxy
    file: ci/scripts/etcd/run-unit-test-suite/task.yml
    params:
      TEST_SUITE: etcd-proxy

- name: test-etcd-consistency-checker
  public: true
  plan:
  - aggregate:
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - check-git-submodules
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test-etcd-consistency-checker
    file: ci/scripts/etcd/run-unit-test-suite/task.yml
    params:
      TEST_SUITE: etcd-consistency-checker

- name: test-etcdfab
  public: true
  plan:
  - aggregate:
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - check-git-submodules
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test-etcdfab
    file: ci/scripts/etcd/run-unit-test-suite/task.yml
    params:
      TEST_SUITE: etcdfab

- name: test-etcd-metrics-server
  public: true
  plan:
  - aggregate:
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - check-git-submodules
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test-etcd-metrics-server
    file: ci/scripts/etcd/test-etcd-metrics-server/task.yml

- name: eats
  public: true
  plan:
  - aggregate:
    - get: etcd-release
      resource: etcd-release-develop
      passed:
      - test-etcdfab
      - test-etcd-consistency-checker
      - test-etcd-proxy
      - test-etcd-metrics-server
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
    - get: cf-deployment-concourse-tasks
    - get: stemcell
      resource: gcp-stemcell
    - get: turbulence-release
    - get: consul-release
    - get: latest-etcd-release
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: eats
      BBL_ENV_NAME: eats
      LB_DOMAIN: eats.infrastructure.cf-app.com
      BBL_LB_CERT: {{etcd_cf_deployment_lb_cert}}
      BBL_LB_KEY: {{etcd_cf_deployment_lb_key}}
      GIT_COMMIT_EMAIL: cf-infrastructure@pivotal.io
      GIT_COMMIT_USERNAME: CI Infra Bot
    input_mapping:
      ops-files: bbl-state
    on_failure:
      do:
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: eats
        input_mapping:
          bbl-state: updated-bbl-state
  - task: run-eats
    file: ci/scripts/etcd/run-eats/task.yml
    params:
      BBL_STATE_DIR: eats
      ENABLE_TURBULENCE_TESTS: false
      PARALLEL_NODES: 5
    input_mapping:
      bbl-states-repo: updated-bbl-state
    ensure:
      do:
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: eats
        input_mapping:
          bbl-state: updated-bbl-state

- name: deploy-sample-manifests
  public: true
  plan:
  - aggregate:
    - get: release
      resource: etcd-release-develop
      passed:
      - eats
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: bosh-deployment
    - get: bosh-lite-stemcell
  - task: deploy-sample-manifests
    file: ci/scripts/common/deploy-sample-manifests/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      CLOUD_CONFIG: manifests/cloud-config.yml
      MANIFESTS: manifests/3-node-with-ssl.yml manifests/3-node-no-ssl.yml manifests/3-node-with-proxy.yml
      DEPENDENCIES: cloudfoundry-incubator/consul-release

- name: cats
  public: true
  plan:
  - aggregate:
    - get: release
      resource: etcd-release-develop
      passed:
      - test-etcdfab
      - test-etcd-consistency-checker
      - test-etcd-proxy
      - test-etcd-metrics-server
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
    - get: cf-deployment-concourse-tasks
    - get: cf-acceptance-tests
    - get: cats-concourse-task
    - get: cf-deployment
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: etcd-cf-cats
      BBL_ENV_NAME: etcd-cf-cats
      LB_DOMAIN: etcd-cf-cats.infrastructure.cf-app.com
      BBL_LB_CERT: {{etcd_cf_deployment_lb_cert}}
      BBL_LB_KEY: {{etcd_cf_deployment_lb_key}}
    input_mapping:
      ops-files: bbl-state
    on_failure:
      do:
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: cats
        input_mapping:
          bbl-state: updated-bbl-state
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-cats
    input_mapping:
      bbl-state: updated-bbl-state
  - task: deploy
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-cats
      SYSTEM_DOMAIN: etcd-cf-cats.infrastructure.cf-app.com
      VARS_STORE_FILE: etcd-cf-cats/deployment-vars.yml
    input_mapping:
      bbl-state: updated-bbl-state
      ops-files: updated-bbl-state
      vars-store: updated-bbl-state
      vars-files: updated-bbl-state
  - task: run-cats
    file: cats-concourse-task/task.yml
    params:
      CONFIG_FILE_PATH: artifacts/cats_config.json
    input_mapping:
      integration-config: updated-integration-configs
    ensure:
      do:
      - task: delete-cf-deployment
        file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-cats
        input_mapping:
          bbl-state: updated-bbl-state
      - task: cleanup-cf-deployment
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-cats
        input_mapping:
          bbl-state: updated-bbl-state
      - task: remove-from-gcp-dns
        file: ci/scripts/common/manage-gcp-dns/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-cats
          GCP_DNS_PROJECT_ID: {{cf_infra_gcp_project_id}}
          GCP_DNS_SERVICE_ACCOUNT_EMAIL: {{cf_infra_gcp_service_account_email}}
          GCP_DNS_SERVICE_ACCOUNT_KEY: {{cf_infra_gcp_service_account_key}}
          GCP_DNS_ZONE_NAME: infrastructure
          GCP_DNS_RECORD_SET_NAME: etcd-cf-cats.infrastructure.cf-app.com
          ACTION: remove
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: cats
        input_mapping:
          bbl-state: updated-bbl-state

- name: cf-tls-upgrade
  public: true
  plan:
  - aggregate:
    - get: release
      resource: etcd-release-develop
      passed:
      - test-etcdfab
      - test-etcd-consistency-checker
      - test-etcd-proxy
      - test-etcd-metrics-server
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      BBL_ENV_NAME: etcd-cf-tls-upgrade
      LB_DOMAIN: etcd-cf-tls-upgrade.infrastructure.cf-app.com
      BBL_LB_CERT: {{etcd_cf_tls_upgrade_lb_cert}}
      BBL_LB_KEY: {{etcd_cf_tls_upgrade_lb_key}}
    input_mapping:
      ops-files: bbl-state
    on_failure:
      do:
      - task: bbl-destroy
        file: ci/scripts/common/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-tls-upgrade
        input_mapping:
          bbl-states-repo: updated-bbl-state
  - task: add-to-gcp-dns
    file: ci/scripts/common/manage-gcp-dns/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      GCP_DNS_PROJECT_ID: {{cf_infra_gcp_project_id}}
      GCP_DNS_SERVICE_ACCOUNT_EMAIL: {{cf_infra_gcp_service_account_email}}
      GCP_DNS_SERVICE_ACCOUNT_KEY: {{cf_infra_gcp_service_account_key}}
      GCP_DNS_ZONE_NAME: infrastructure
      GCP_DNS_RECORD_SET_NAME: etcd-cf-tls-upgrade.infrastructure.cf-app.com
      ACTION: add
    input_mapping:
      bbl-states-repo: updated-bbl-state
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
    input_mapping:
      bbl-state: updated-bbl-state
  - task: deploy
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      OPS_FILES: scripts/etcd/test-cf-tls-upgrade/opsfiles/non-tls-cf-deployment.yml
      SYSTEM_DOMAIN: etcd-cf-tls-upgrade.infrastructure.cf-app.com
      VARS_STORE_FILE: etcd-cf-tls-upgrade/deployment-vars.yml
    input_mapping:
      bbl-state: updated-bbl-state
  - task: run-cf-tls-upgrade
    file: ci/scripts/etcd/test-cf-tls-upgrade/task.yml
    params:
      BBL_STATE_DIR: etcd-cf-tls-upgrade
      CF_DOMAIN: {{etcd_cf_domain}}
    ensure:
      do:
      - task: delete-cf-deployment
        file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-tls-upgrade
      - task: cleanup-cf-deployment
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-tls-upgrade
      - task: remove-from-gcp-dns
        file: ci/scripts/common/manage-gcp-dns/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-tls-upgrade
          GCP_DNS_PROJECT_ID: {{cf_infra_gcp_project_id}}
          GCP_DNS_SERVICE_ACCOUNT_EMAIL: {{cf_infra_gcp_service_account_email}}
          GCP_DNS_SERVICE_ACCOUNT_KEY: {{cf_infra_gcp_service_account_key}}
          GCP_DNS_ZONE_NAME: infrastructure
          GCP_DNS_RECORD_SET_NAME: etcd-cf-tls-upgrade.infrastructure.cf-app.com
          ACTION: remove
      - task: bbl-destroy
        file: ci/scripts/common/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: etcd-cf-tls-upgrade
        input_mapping:
          bbl-states-repo: updated-bbl-state

- name: create-final-release
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo
      resource: etcd-release-develop
      passed:
      - eats
      - cats
      - cf-tls-upgrade
      trigger: true
    - get: release-repo-master
      resource: etcd-release-master
    - get: oss-s3-buckets-stack
  - task: create-final-release
    file: ci/scripts/common/create-final-release/task.yml
    params:
      RELEASE_NAME: etcd
  - put: etcd-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo-master
      trigger: true
      resource: etcd-release-master
    - get: release-repo
      resource: etcd-release-merge-target
  - task: merge-master-into-develop
    file: ci/scripts/common/merge-master-into-develop/task.yml
  - put: etcd-release-merge-target
    params:
      repository: final-release-repo
