groups:
- name: gomegamatchers
  jobs:
  - test-gomegamatchers

resources:
- name: gomegamatchers
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/gomegamatchers.git
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

jobs:
- name: test-gomegamatchers
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: gomegamatchers
      trigger: true
  - task: test
    file: ci/scripts/gomegamatchers/task.yml
