groups:
- name: terraforming
  jobs:
  - terraforming-aws

resources:
- name: terraforming-aws
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/terraforming-aws.git
    private_key: {{cf_infra_bot_user_github_private_key}}
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

jobs:
- name: terraforming-aws
  public: true
  plan:
  - get: terraforming-aws
    trigger: true
  - get: ci
    resource: infrastructure-ci
  - task: check-syntax
    file: ci/scripts/terraforming/check-aws-syntax/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
